/* Generated By:JJTree&JavaCC: Do not edit this line. teaConstants.java */
public interface teaConstants {

  int EOF = 0;
  int VOIDTYPE = 5;
  int DATATYPE = 6;
  int IF_KEYWORD = 7;
  int ELSE_KEYWORD = 8;
  int DO_KEYWORD = 9;
  int WHILE_KEYWORD = 10;
  int FOR_KEYWORD = 11;
  int LBRACE = 12;
  int RBRACE = 13;
  int LPAREN = 14;
  int RPAREN = 15;
  int SEMICOLON = 16;
  int ASSIGNOP = 17;
  int OR_OP = 18;
  int AND_OP = 19;
  int EQ_OP = 20;
  int NEQ_OP = 21;
  int LT_OP = 22;
  int LT_EQ_OP = 23;
  int GT_OP = 24;
  int GT_EQ_OP = 25;
  int PLUS_OP = 26;
  int MINUS_OP = 27;
  int MUL_OP = 28;
  int DIV_OP = 29;
  int MOD_OP = 30;
  int LNEG = 31;
  int COMMA = 32;
  int NAME = 33;
  int NUMBER = 34;
  int OTHER = 35;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"void\"",
    "\"int\"",
    "\"if\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "\"for\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\",\"",
    "<NAME>",
    "<NUMBER>",
    "<OTHER>",
  };

}
