/* Generated By:JJTree: Do not edit this line. teaTreeConstants.java */

public interface teaTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMETHOD_DECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTDECLARATIVE_STATEMENT = 3;
  public int JJTASSIGNMENT_STATEMENT = 4;
  public int JJTOR_EXPRESSION = 5;
  public int JJTAND_EXPRESSION = 6;
  public int JJTRELOP_EXPRESSION = 7;
  public int JJTLTGT_EXPRESSION = 8;
  public int JJTADDOP_EXPRESSION = 9;
  public int JJTMULOP_EXPRESSION = 10;
  public int JJTTERM = 11;
  public int JJTVALUE = 12;
  public int JJTIF_STATEMENT = 13;
  public int JJTWHILE_STATEMENT = 14;
  public int JJTDO_WHILE_STATEMENT = 15;
  public int JJTFOR_STATEMENT = 16;


  public String[] jjtNodeName = {
    "program",
    "method_declaration",
    "void",
    "declarative_statement",
    "assignment_statement",
    "or_expression",
    "and_expression",
    "relop_expression",
    "ltgt_expression",
    "addop_expression",
    "mulop_expression",
    "term",
    "value",
    "if_statement",
    "while_statement",
    "do_while_statement",
    "for_statement",
  };
}
