include libsx_defs

project : renderer modeler

renderer : renderer.cpp definitions.h
	   g++ -o renderer renderer.cpp $(PETERG)
modeler : modeler.cpp definitions.h
	   g++ -o modeler modeler.cpp $(PETERG)

