/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>


#define PGNFS_PROG ((u_int)0x13080077)
#define PGNFS_VER ((u_int)1)
#define SENDCOMMAND ((u_int)1)
extern char **sendcommand_1();
extern void fs_init();