/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "pgnfs.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

char **
sendcommand_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static char *res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, SENDCOMMAND, xdr_wrapstring, argp, xdr_wrapstring, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}
